module.exports = {
  NAME_TAKEN: 'NAME_TAKEN',
  NOT_FOUND: 'NOT_FOUND',
  WRONG_PW: 'WRONG_PW',
  GREETING_NOTE_MSG: 'Welcome! This is my first note.',
  NO_ACCESS: 'NO_ACCESS',
  SERVER_ERROR: 'SERVER_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FORM_FIELDS_MISSING: 'FORM_FIELDS_MISSING',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  APP_URL: 'appurl.io'
};
